DELETE FROM `command` WHERE (`name`='bg end');
DELETE FROM `command` WHERE (`name`='bg update');
DELETE FROM `command` WHERE (`name`='bg list');
DELETE FROM `command` WHERE (`name`='bg debug');
-- DELETE FROM `command` WHERE (`name`='bg join');
-- DELETE FROM `command` WHERE (`name`='bg create');
INSERT INTO `command` (`name`,`security`,`help`) VALUES ('bg update','3',"Syntax: .bg update $seconds [$shift-bglink]\r\nIf $shift-bglink isn't used it takes the bg of the targeted player or bg from current player.\r\nThen bg gets an 'BattleGround::Update'-call with $seconds.\r\nSo a .bg update 120 at the beginning, will let your bg instantly start.");
INSERT INTO `command` (`name`,`security`,`help`) VALUES ('bg end','3',"Syntax: .bg end $winner [$shift-bglink]\r\nIf $shift-bglink isn't used it takes the bg of the targeted player or current player\r\nThen bg gets ended with a $winner.\r\n(Winnner=0->Horde,Winner=1->Alliance, else ->Draw)");
INSERT INTO `command` (`name`,`security`,`help`) VALUES ('bg list','3',"Syntax: .bg list [bg-shiftlink]\r\nLists all current open Battlegrounds and arenas - with some information about them.\r\nIf the optional bg-shiftlink parameter is given, it just shows bgs/arenas of the same type.\r\nFor arenas it means, shows only 2v2,3v3,5v5 and for bgs it shows av,ab,ey,wsg.");
INSERT INTO `command` (`name`,`security`,`help`) VALUES ('bg debug','3',"Syntax: .bg debug\r\nToggle debug mode for battlegrounds. In debug mode GM can start battleground with single player.");
-- INSERT INTO `command` (`name`,`security`,`help`) VALUES ('bg join','3',"Syntax: .bg join\r\n.");
-- INSERT INTO `command` (`name`,`security`,`help`) VALUES ('bg create','3',"Syntax: .bg create\r\n.");
